package net.worldbinder.export.common;

import net.worldbinder.scene.WorldScene;
import net.worldbinder.version.TargetMinecraftVersion;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;

public final class ExportReadmeWriter {
    private ExportReadmeWriter() {
    }

    public static void write(WorldScene scene, Path worldFolder, int chunkCount) throws IOException {
        TargetMinecraftVersion.Entry target = TargetMinecraftVersion.resolve(scene == null ? null : scene.targetMinecraftVersion);
        List<String> serverKeys = ExportPathUtil.serverImportKeys(scene, worldFolder);
        String keyText = serverKeys.isEmpty() ? "minecraft:overworld" : "minecraft:" + String.join(", minecraft:", serverKeys);
        String name = scene == null || scene.name == null || scene.name.isBlank() ? "WorldBinder Export" : scene.name;
        String minecraftVersion = scene == null || scene.minecraftVersion == null || scene.minecraftVersion.isBlank() ? "unknown" : scene.minecraftVersion;
        int blocks = scene == null ? 0 : scene.blockCount();
        int blockEntities = scene == null ? 0 : scene.blockEntityCount();
        int entities = scene == null ? 0 : scene.entityCount();

        String content = """
                # WorldBinder Export

                This folder was generated by WorldBinder.

                ## Export summary

                | Field | Value |
                | --- | --- |
                | Export name | %s |
                | Created | %s |
                | Captured client version | %s |
                | Target output version | %s |
                | Target profile | %s |
                | Chunks written | %s |
                | Blocks captured | %s |
                | Block entities captured | %s |
                | Entities captured | %s |

                ## Folder layout

                This export is written as a Minecraft world save. Depending on the selected target version, it may contain:

                - `level.dat` and `level.dat_old`
                - `session.lock`
                - `icon.png`
                - root-level `region/`, `entities/` and `poi/` folders for server imports
                - `dimensions/minecraft/overworld/` for modern 26.x compatibility
                - `data/minecraft/` saved-data files
                - `resources.zip` when a server resource pack was available
                - `worldbinder/` metadata and validation reports

                ## Server import notes

                For Paper or Multiverse-style imports, copy this whole folder into the server world directory and import it with your normal server tools.

                WorldBinder writes server-friendly root region folders and, for 26.x exports, modern dimension mirrors. The detected server world key(s) for this export are:

                `%s`

                If your server imports the world under a different name, check the spawn and first loaded chunks after import.

                ## Limitations

                WorldBinder can only export data the client actually received. Missing chunks, hidden entities, inventories, server-side systems, datapack logic or protected resource packs cannot always be reconstructed.

                Review `worldbinder/export_validation.json` or `worldbinder/EXPORT_VALIDATION.txt` when available before publishing or permanently importing the export.

                ## Responsible use

                Use this export only if you own the content, administer the server, created the build yourself, or have explicit permission to archive or export it.
                """.formatted(
                name,
                Instant.now(),
                minecraftVersion,
                target.name(),
                target.profile().label(),
                chunkCount,
                blocks,
                blockEntities,
                entities,
                keyText
        );
        Files.writeString(worldFolder.resolve("README.md"), content);
    }
}
